name: chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  animate_do: ^4.2.0
  lottie: ^3.3.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  intl: ^0.17.0
  image_picker: ^1.0.4
  permission_handler: ^12.0.0+1
  flutter_sound: ^9.2.13
  google_sign_in: ^6.3.0
  http: ^1.4.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  mailer: ^6.4.1
  firebase_messaging: ^15.2.5
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  file_picker: ^10.1.7
  curved_navigation_bar: ^1.0.6
  audioplayers: ^6.4.0
  video_player: ^2.9.5
  chewie: ^1.11.3
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  async: ^2.12.0
  connectivity_plus: ^6.1.4
  just_audio: ^0.10.2
  record: ^6.0.0
  cloudinary_public: ^0.23.1
  provider: ^6.1.3
  iconsax_flutter: ^1.0.0
  audio_video_progress_bar: ^2.0.3
  percent_indicator: ^4.2.5
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Add this here to avoid errors

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/default_avatar.jpeg
    - assets/images/Main_Logo.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/default_avatar.jpeg"
