name: chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

assets:
  - assets/images/

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  animate_do: ^4.2.0
  lottie: ^3.3.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  image_picker: ^1.0.4
  permission_handler: ^12.0.0+1
  flutter_sound: ^9.2.13
  google_sign_in: ^6.3.0
  http: ^1.4.0
  file_picker: ^10.1.7
  curved_navigation_bar: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  


flutter:
  uses-material-design: true
