name: chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

assets:
  - assets/images/

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  animate_do: ^3.0.1
  lottie: ^2.2.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2


flutter:
  uses-material-design: true
